//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public int pprice { get; set; }
        public int pquantity { get; set; }
        public string pinfo { get; set; }
        public string pimg { get; set; }
    }
}
